apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-allow-gateway-only
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: redis            
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: gateway
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.prometheus.namespace }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.redis_exporter.podLabels | nindent 14 }}
      ports:
        - port: {{ .Values.redis.port }}
{{- if .Values.prometheus.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.prometheus.namespace }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.prometheus.podLabels | nindent 14 }}
      ports:
        - port: {{ .Values.redis.port }}
{{- end }} 