apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-deployment
  namespace: intelliserve
  labels: 
    app: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: inference
        image: api-gateway-inference-engine:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: intelliserve-config
        - secretRef:
            name: inference-token-secret
        startupProbe:
          httpGet:
            path: /live
            port: 80
          periodSeconds: 5
          failureThreshold: 24
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 8
        livenessProbe:
          httpGet:
            path: /live
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 8
        # resources:
        #   requests:
        #     cpu: "4"
        #     memory: "2500Mi"
        #   limits:
        #     cpu: "6"
        #     memory: "3Gi"