services:
  redis-server:
    image: 'redis'
  intent-classifier:
    build: ../intent-classifier
    volumes: 
      - ../intent-classifier/models:/intent_classifier/models
  inference-engine:
    build: ../inference-engine
    env_file:
      - ../inference-engine/.env
  api-gateway:
    build: .
    depends_on:
      redis-server:
        condition: service_started
      intent-classifier:
        condition: service_started
    env_file:
      - ./.env
    ports:
      - "8000:80"