apiVersion: v1
kind: ResourceQuota
metadata:
  name: intelliserver-quota
  namespace: intelliserve
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "6Gi"
    limits.cpu: "10"
    limits.memory: "7Gi"