apiVersion: v1
kind: LimitRange
metadata:
  name: intelliserve-default-limits
  namespace: intelliserve
spec:
  limits:
  - type: Container
    default:
      cpu: {{ .Values.limitRange.defaultLimitCpu }}
      memory: {{ .Values.limitRange.defaultLimitMemory }}
    defaultRequest:
      cpu: {{ .Values.limitRange.defaultRequestCpu }}
      memory: {{ .Values.limitRange.defaultRequestMemory }}