apiVersion: v1
kind: ResourceQuota
metadata:
  name: intelliserver-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.ResourceQuota.requestscpu | quote }}
    requests.memory: {{ .Values.ResourceQuota.requestsmemory }}
    limits.cpu: {{ .Values.ResourceQuota.limitscpu | quote }}
    limits.memory: {{ .Values.ResourceQuota.limitsmemory }}