apiVersion: apps/v1
kind: Deployment 
metadata:
  name: gateway-deployment
  namespace: intelliserve
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: api-gateway-api-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: intelliserve-config
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 8
        livenessProbe:
          httpGet:
            path: /live
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 8
        # resources:
        #   requests: 
        #     cpu: "50m"
        #     memory: "64Mi"
        #   limits:
        #     cpu: "500m"
        #     memory: "256Mi"