apiVersion: v1
kind: Service
metadata: 
  name: intent-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: intent
  ports:
  - port: {{ .Values.intentClassifier.port }}
    targetPort: {{ .Values.intentClassifier.targetPort }}