apiVersion: apps/v1
kind: Deployment
metadata:
  name: intent-deployment
  namespace: intelliserve
  labels:
    app: intent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intent
  template:
    metadata:
      labels:
        app: intent
    spec:
      containers:
      - name: intent
        image: api-gateway-intent-classifier:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: intelliserve-config
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 8
        livenessProbe:
          httpGet:
            path: /live
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 8
        # resources:
        #   requests: 
        #     cpu: "600m"
        #     memory: "400Mi"
        #   limits:
        #     cpu: "700m"
        #     memory: "512Mi"

